### ISSUE TITLE
CS0655 with ArgAttribute.ShortName

### ISSUE THREAD

**Issue by Ghost4Man** [ruibm/Danio#3]
I get this error (Program.cs line 20):

> CS0655: 'ShortName' is not a valid named attribute argument because it is not a valid attribute parameter type

whenever I try to use the ShortName parameter of the ArgAttribute. Apparently C# doesn't support `char?` as an attribute parameter type... 
This is from the ECMA C# Specification:

> 24.1.3 Attribute parameter types
> The types of positional and named parameters for an attribute class are limited to the attribute parameter types, which are:
> - One of the following types: bool, byte, char, double, float, int, long, short, string.
> - The type object.
> - The type System.Type.
> - An enum type, provided it has public accessibility and the types in which it is nested (if any) also have public accessibility.
> - Single-dimensional arrays of the above types.

**Comment by thomasjungblut** [comment]
What visual studio and .NET framework version are you using to compile?

**Comment by Ghost4Man** [comment]
_Visual Studio Community 2015, Version 14.0.25431.01 Update 3_
I tried compiling with .NET Framework 4.6.1, 4.5.1, 4.5, and 4. It doesn't work in either of them.

**Comment by thomasjungblut** [comment]
That's odd, I have it running and compiling with VS2013 and .NET 4.5 and 4.5.1. Let me download and install community 15.

**Comment by Ghost4Man** [comment]
Have you looked at the C# specs? I think it **should not** work, because the `char?` (`Nullable<char>`) type is simply not supported in parameters of attributes. Instead, I think it's strange that it works for you... Are you sure you're using the `ShortName` parameter? I looked at the samples and tests, and it doesn't seem to be used anywhere in the code...

**Comment by thomasjungblut** [comment]
Apologies, indeed there is no example covering the `ShortName` and I also get CS0655 when adding it. 
I think we should remove the Nullable<char> and simply use a string, are you interested in doing this change @Ghost4Man? Otherwise I have a few minutes to spare tomorrow evening.

**Comment by Ghost4Man** [comment]
Well, I don't have much experience with contributing or Git yet, so I will leave it to you.
Maybe next time :smile:

**Comment by thomasjungblut** [comment]
fixed 👍
